services:
  - type: web
    name: day12-v2
    runtime: docker
    region: singapore
    plan: starter
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DEFAULT_PROVIDER
        value: openai
      - key: DEFAULT_MODEL
        value: gpt-4o
      - key: LOG_LEVEL
        value: INFO
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AGENT_API_KEY
        sync: false
